In [1]:
from sklearn.preprocessing import LabelEncoder
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('final_data.csv')

In [3]:
label_encoder = LabelEncoder()
df['Loại Nhà (mã hóa)'] = label_encoder.fit_transform(df['Loại nhà'])
encoded_values_loai = df[['Loại nhà', 'Loại Nhà (mã hóa)']].drop_duplicates().sort_values('Loại Nhà (mã hóa)')
print(encoded_values_loai)

           Loại nhà  Loại Nhà (mã hóa)
0   Căn hộ chung cư                  0
20      Nhà mặt phố                  1
19        Nhà riêng                  2

In [4]:
df['Quận (mã hóa)'] = label_encoder.fit_transform(df['Quận'])
encoded_values_quan = df[['Quận', 'Quận (mã hóa)']].drop_duplicates().sort_values('Quận (mã hóa)')
print(encoded_values_quan)

              Quận  Quận (mã hóa)
39         Ba Đình              0
28     Bắc Từ Liêm              1
678      Chương Mỹ              2
20        Cầu Giấy              3
0          Gia Lâm              4
6     Hai Bà Trưng              5
79        Hoài Đức              6
218      Hoàn Kiếm              7
99       Hoàng Mai              8
2          Hà Đông              9
14       Long Biên             10
2015       Mê Linh             11
1      Nam Từ Liêm             12
104       Quốc Oai             13
5305       Sóc Sơn             14
543        Sơn Tây             15
539      Thanh Oai             16
50       Thanh Trì             17
33      Thanh Xuân             18
19      Thường Tín             19
1823    Thạch Thất             20
51          Tây Hồ             21
529     Đan Phượng             22
356       Đông Anh             23
38         Đống Đa             24

In [5]:
df['Khoảng giá'] = df['Mức giá (tỷ)'].apply(lambda x: 0 if x <= 2 else (1 if x < 10 else (2 if x < 50 else 3)))

df_low = df[df['Khoảng giá']==0]
df_low_avg = df[df['Khoảng giá']==1]
df_high_avg = df[df['Khoảng giá']==2]
df_high = df[df['Khoảng giá']==3]
print(df_low.shape[0])
print(df_low_avg.shape[0])
print(df_high_avg.shape[0])
print(df_high.shape[0])

319
5345
1995
234

In [6]:
# Bổ sung thêm cột Mức giá (triệu/m²)
df['Mức giá (triệu/m²)'] = df['Mức giá (tỷ)'] * 1000 / df['Diện tích (m²)']

# Xóa tất cả các dòng có giá trị quá lớn trong cột 'Mức giá (triệu/m²)' (lớn hơn 2000)
df = df.drop(df[df['Mức giá (triệu/m²)'] > 2000].index)

In [7]:
df

,Quận,Loại nhà,Diện tích (m²),Mức giá (tỷ),Số phòng ngủ,Số toilet,Loại Nhà (mã hóa),Quận (mã hóa),Khoảng giá,Mức giá (triệu/m²)
0,Gia Lâm,Căn hộ chung cư,55.0,2.07,2,1,0,4,1,37.636364
1,Nam Từ Liêm,Căn hộ chung cư,140.0,9.50,4,3,0,12,1,67.857143
2,Hà Đông,Căn hộ chung cư,98.0,3.19,3,2,0,9,1,32.551020
3,Nam Từ Liêm,Căn hộ chung cư,59.0,2.90,2,2,0,12,1,49.152542
4,Hà Đông,Căn hộ chung cư,92.0,3.50,2,2,0,9,1,38.043478
...,...,...,...,...,...,...,...,...,...,...
7888,Bắc Từ Liêm,Căn hộ chung cư,98.0,6.35,3,2,0,1,1,64.795918
7889,Hà Đông,Nhà mặt phố,225.0,66.00,6,8,1,9,3,293.333333
7890,Nam Từ Liêm,Nhà riêng,40.0,4.00,4,4,2,12,1,100.000000
7891,Gia Lâm,Căn hộ chung cư,70.0,2.45,2,2,0,4,1,35.000000
7892,Tây Hồ,Nhà riêng,300.0,97.00,36,22,2,21,3,323.333333

In [8]:
# Lưu dataframe vào file CSV
df.to_csv('encode_data.csv', index=False)

print("Dữ liệu đã được lưu vào file encode_data.csv thành công.")

Dữ liệu đã được lưu vào file encode_data.csv thành công.